name: Trigger-All-Toolchain-Workflows  # 主要工作流的名称
#CI权限
permissions:
  contents: write
  actions: write
on:
  workflow_dispatch:  # 手动触发：通过 GitHub UI 来触发
  schedule:
    - cron: 1 16 * * 5  # 北京时间星期六凌晨0点，定时触发

jobs:

  IPQ60XX-6_12-Libwrt:
    uses: ./.github/workflows/Compile-Toolchain.yml
    with:
      WRT_TARGET: 'IPQ60XX'

  IPQ807X-6_12-Libwrt:
    uses: ./.github/workflows/Compile-Toolchain.yml
    with:
      WRT_TARGET: 'IPQ807X'

#  JDCloud-6_12-Libwrt:
#    uses: ./.github/workflows/Compile-Toolchain.yml
#    with:
#      WRT_TARGET: 'JDCloud'

  x86-64-6_12-Immortalwrt:
    uses: ./.github/workflows/Compile-Toolchain.yml
    with:
      WRT_TARGET: 'x86-64'
      WRT_SOURCE: 'immortalwrt/immortalwrt'
      WRT_BRANCH: 'master'

  #RAX3000M-6_12-Immortalwrt:
  #  uses: ./.github/workflows/Compile-Toolchain.yml
  #  with:
  #    WRT_TARGET: 'RAX3000M'
  #    WRT_SOURCE: 'immortalwrt/immortalwrt'
  #    WRT_BRANCH: 'master'

  Delete-Old-Workflows:
    uses: ./.github/workflows/Delete-Old-Workflows.yml
