name: Trigger-All-Workflows  # 主要工作流的名称
#CI权限
permissions:
  contents: write
  actions: write
on:
  workflow_dispatch:  # 手动触发：通过 GitHub UI 来触发
  schedule:
    - cron: 0 18 * * 5  # 北京时间星期六凌晨2点，定时触发

jobs:

  IPQ53XX-6_18-immortalwrt:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_TARGET: 'IPQ53XX'
      WRT_SOURCE: 'VIKINGYFY/immortalwrt'
      WRT_BRANCH: 'owrt'
      WRT_FIRMWARE_BODY: '这是基于immortal源码主线分支添加iStore编译的6.18内核固件，默认主题为Argon'

  IPQ60XX-6_12-Libwrt:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_TARGET: 'IPQ60XX'
      WRT_SOURCE: 'LiBwrt/LibWrt'
      WRT_BRANCH: '25.12-nss'

  IPQ807X-6_12-Libwrt:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_TARGET: 'IPQ807X'
      WRT_SOURCE: 'LiBwrt/LibWrt'
      WRT_BRANCH: '25.12-nss'

  JDCloud-6_12-Libwrt:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_TARGET: 'JDCloud'
      WRT_SOURCE: 'LiBwrt/LibWrt'
      WRT_BRANCH: '25.12-nss'

  JDCloud-6_12-Libwrt-NoWiFi:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_TARGET: 'JDCloud.NoWiFi'
      WRT_SOURCE: 'LiBwrt/LibWrt'
      WRT_BRANCH: '25.12-nss'

  JDCloud-6_12-immortalwrt:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_TARGET: 'JDCloud'
      WRT_SOURCE: 'immortalwrt/immortalwrt'
      WRT_BRANCH: 'master'
      WRT_PACKAGE: 'luci-app-oaf=n luci-app-easymesh=n'
      WRT_FIRMWARE_BODY: '这是基于immortal源码24.10分支添加iStore编译的有WiFi固件，默认主题为Argon'

  JDCloud-6_12-immortalwrt-NoWiFi:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_TARGET: 'JDCloud.NoWiFi'
      WRT_SOURCE: 'immortalwrt/immortalwrt'
      WRT_BRANCH: 'master'
      WRT_PACKAGE: 'luci-app-oaf=n'
      WRT_FIRMWARE_BODY: '这是基于immortal源码24.10分支添加iStore编译的无WiFi固件，默认主题为Argon'

  x86-64-6_12-Immortalwrt:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_TARGET: 'x86-64'
      WRT_SOURCE: 'immortalwrt/immortalwrt'
      WRT_BRANCH: 'master'
      WRT_FIRMWARE_BODY: '这是基于ImmortalWrt主线制作的x86-64个人定制固件，默认主题为Argon'

  #RAX3000M-6_12-Immortalwrt:
  #  uses: ./.github/workflows/WRT-CORE.yml
  #  with:
  #    WRT_TARGET: 'RAX3000M'
  #    WRT_SOURCE: 'immortalwrt/immortalwrt'
  #    WRT_BRANCH: 'master'
  #    WRT_FIRMWARE_BODY: '这是CMCC RAX3000M 基于ImmortalWrt主线制作的个人定制固件，默认主题为Argon'
  #    # WRT_FIRMWARE_BODY: '这是CMCC RAX3000M NAND version (custom U-Boot layout)的5.15内核固件，默认主题为Argon'

  Delete-Old-Workflows:
    uses: ./.github/workflows/Delete-Old-Workflows.yml
