name: WRT-CORE
#CI权限
permissions:
  contents: write
  actions: write
on:
  workflow_call:
    inputs:
      WRT_TARGET:
        description: '编译平台. [ JDCloud, IPQ50XX, IPQ53XX, IPQ60XX, IPQ807X, x86-64 ]'
        required: true
        type: string
        default: 'IPQ60XX'
      WRT_SOURCE:
        description: '源码仓库名. [ LiBwrt/LibWrt, VIKINGYFY/immortalwrt, immortalwrt/immortalwrt ]'
        required: false
        type: string
        default: 'LiBwrt/LibWrt'
      WRT_BRANCH:
        description: '源码分支名. [ master, main, main-nss, 25.12-nss, owrt, openwrt-24.10, openwrt-25.12 ]'
        required: false
        type: string
        default: '25.12-nss'
      WRT_PACKAGE:
        description: '添加编译包全名 luci-app-xxx=y 多个用空格分开'
        required: false
        type: string
      WRT_CONFIG:
        description: '添加完整编译配置项，多个用空格分开'
        required: false
        type: string
      WRT_FIRMWARE_BODY:
        description: 'Release 说明信息'
        required: false
        type: string
        default: '这是开启全功能NSS的6.12内核固件，默认主题为Argon'
  workflow_dispatch:
    inputs:
      WRT_TARGET:
        default: 'JDCloud'
        required: true
        type: choice
        description: '配置文件名'
        options: [ 'JDCloud', 'IPQ50XX', 'IPQ53XX', 'IPQ60XX', 'IPQ807X', 'x86-64' ]
      WRT_SOURCE:
        description: '源码仓库名'
        required: true
        default: 'LiBwrt/LibWrt'
        type: choice
        options: [ 'LiBwrt/LibWrt', 'VIKINGYFY/immortalwrt', 'immortalwrt/immortalwrt' ]
      WRT_BRANCH:
        default: '25.12-nss'
        required: true
        description: 'branch name'
        type: choice
        options:
          - master
          - main
          - main-nss
          - 25.12-nss
          - owrt
          - openwrt-24.10
          - openwrt-25.12
      WRT_PACKAGE:
        description: '添加编译包全名 luci-app-xxx=y'
        required: false
        type: string
      WRT_CONFIG:
        description: '添加完整编译配置项'
        required: false
        type: string
      WRT_FIRMWARE_BODY:
        description: 'Release 说明信息'
        required: false
        default: '这是开启全功能NSS的6.12内核固件，默认主题为Argon'
        type: string

env:
  REPO_URL: https://github.com/${{inputs.WRT_SOURCE || 'LiBwrt/LibWrt'}}.git
  REPO_BRANCH: ${{inputs.WRT_BRANCH || '25.12-nss'}}
  CONFIG_FILE: configs/${{inputs.WRT_TARGET}}.config
  GENERAL_CONFIG_FILE: configs/General.config
  FIRMWARE_TAG: ${{inputs.WRT_TARGET}}
  FIRMWARE_BODY: ${{inputs.WRT_FIRMWARE_BODY}}
  TOOLCHAIN_SCRIPT: scripts/HandleToolchain.sh
  TOOLCHAIN_CACHE: true
  TOOLCHAIN_TAG: toolchain-cache
  TZ: Asia/Shanghai

  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  WRT_SOURCE: ${{inputs.WRT_SOURCE}}
  WRT_TARGET: ${{inputs.WRT_TARGET}}
  WRT_PACKAGE: ${{inputs.WRT_PACKAGE}}
  WRT_CONFIG: ${{inputs.WRT_CONFIG}}

jobs:
  Build:
    runs-on: ubuntu-latest
    name: build firmware for ${{ inputs.WRT_TARGET }}

    steps:
      - name: Check Server Performance
        run: |
          echo "警告⚠"
          echo "是否打patch：${{ env.WRT_PATCH }}"
          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
          echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息："
          echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y install dos2unix
          sudo -E apt-get -y install $(curl -fsSL ophub.org/ubuntu2404-make-openwrt-depends)
          sudo -E systemctl daemon-reload
          sudo timedatectl set-timezone "$TZ"

      - name: Combine Disks
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 1024
          temp-reserve-mb: 100
          root-reserve-mb: 1024

      - name: Checkout
        uses: actions/checkout@main

      - name: Clone Source Code
        run: |
          df -hT $GITHUB_WORKSPACE
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          cd openwrt
          echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
          VERSION_INFO=$(git show -s --date=short --format="作者: %an<br/>时间: %cd<br/>内容: %s<br/>hash: %H")
          echo "VERSION_INFO=$VERSION_INFO" >> $GITHUB_ENV

      - name: Generate Variables
        run: |
          cp $CONFIG_FILE $OPENWRT_PATH/.config
          cd $OPENWRT_PATH
          make defconfig > /dev/null 2>&1
          SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
          echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
          DEVICE_TARGET=$(cat .config | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}')
          echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
          DEVICE_SUBTARGET=$(cat .config | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}')
          echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
          
          # toolchain缓存文件名
          CACHE_NAME_PREFIX="$SOURCE_REPO-${REPO_BRANCH#*-}-$DEVICE_TARGET-$DEVICE_SUBTARGET-cache"
          echo "CACHE_NAME_PREFIX=$CACHE_NAME_PREFIX" >> $GITHUB_ENV
          TOOLS_HASH=$(git log -1 --pretty=format:"%h" tools toolchain)
          CACHE_NAME="$CACHE_NAME_PREFIX-$TOOLS_HASH"
          echo "CACHE_NAME=$CACHE_NAME" >> $GITHUB_ENV
          
          export WRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          export WRT_CI=$(basename $GITHUB_WORKSPACE)

          echo "WRT_DATE=$WRT_DATE" >> $GITHUB_ENV
          echo "WRT_CI=$WRT_CI" >> $GITHUB_ENV
          echo "FIRMWARE_SOURCE=$(basename $WRT_SOURCE)" >> $GITHUB_ENV

      - name: Check Scripts
        run: |
          find ./ -maxdepth 3 -type f -iregex ".*\(txt\|sh\)$" -exec dos2unix {} \; -exec chmod +x {} \;

      - name: Install Feeds
        run: |
          cd $OPENWRT_PATH
          
          # sed -i '/nss_packages/ s/^/#/' feeds.conf.default
          #sed -i '$a src-git iStore https://github.com/linkease/istore;main' feeds.conf.default
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Custom Packages
        run: |
          cd $OPENWRT_PATH/package/
          echo "Custom Packages Here."
          $GITHUB_WORKSPACE/scripts/Packages.sh
          $GITHUB_WORKSPACE/scripts/Handles.sh

      - name: Load Custom Configuration
        run: |
          cd $OPENWRT_PATH
          rm -rf ./tmp* ./.config*
          cat $GITHUB_WORKSPACE/$CONFIG_FILE $GITHUB_WORKSPACE/$GENERAL_CONFIG_FILE > .config
          $GITHUB_WORKSPACE/scripts/Settings.sh
          make defconfig

      - name: Load Toolchain Script
        run: |
          cd $OPENWRT_PATH
          chmod +x $GITHUB_WORKSPACE/$TOOLCHAIN_SCRIPT && $GITHUB_WORKSPACE/$TOOLCHAIN_SCRIPT

      - name: Compile Toolchain
        if: env.REBUILD_TOOLCHAIN == 'true'
        id: toolchain
        run: |
          cd $OPENWRT_PATH
          make toolchain/compile -j$(nproc) || make toolchain/compile -j1 V=s
          $GITHUB_WORKSPACE/$TOOLCHAIN_SCRIPT

      - name: Delete Old Toolchain
        if: steps.toolchain.conclusion == 'success' || env.OUTPUT_RELEASE == 'true'
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{env.TOOLCHAIN_TAG}}
          assets: |
            ${{env.CACHE_NAME_PREFIX}}-*
          fail-if-no-assets: false
          fail-if-no-release: false

      - name: Upload Toolchain To Release
        if: steps.toolchain.conclusion == 'success' || env.OUTPUT_RELEASE == 'true'
        uses: softprops/action-gh-release@master
        with:
          name: toolchain-cache
          tag_name: ${{env.TOOLCHAIN_TAG}}
          token: ${{secrets.GITHUB_TOKEN}}
          files: output/*
          body: OpenWrt 工具链缓存

      - name: Download DL Package
        run: |
          cd $OPENWRT_PATH
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Fix Rust CI LLVM 404
        run: |
          cd $OPENWRT_PATH
          RUST_FILE="feeds/packages/lang/rust/Makefile"
          if [ ! -f "$RUST_FILE" ]; then
            echo "❌ Rust Makefile not found!"
            exit 1
          fi
          
          echo "📄 Original:"
          grep -n "download-ci-llvm" "$RUST_FILE" || true
          
          # 替换 --set=llvm.download-ci-llvm=true 为 --set=llvm.download-ci-llvm=false
          sed -i 's/--set=llvm\.download-ci-llvm=true/--set=llvm.download-ci-llvm=false/g' "$RUST_FILE"
          
          # 如果仍然没有 false，再追加（兜底）
          if ! grep -q "download-ci-llvm=false" "$RUST_FILE"; then
            sed -i '/^RUST_BOOTSTRAP_ARGS +=/ s|$| --set=llvm.download-ci-llvm=false|' "$RUST_FILE"
          fi
          
          echo "✅ Patched:"
          grep -n "download-ci-llvm" "$RUST_FILE" || true

      - name: Compile Firmware
        id: compile
        run: |
          cd $OPENWRT_PATH
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
          echo "FILE_DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV

      - name: Check Space Usage
        if: (!cancelled())
        run: df -hT

      - name: Organize Files
        if: steps.compile.outputs.status == 'success'
        run: |
          df -hT
          echo "==============================="
          ls $OPENWRT_PATH/bin/targets/*/*
          echo "==============================="
          cd $OPENWRT_PATH/bin/targets/*/*
          cat config.buildinfo
          cat sha256sums
          echo "VERSION_KERNEL=$(find -type f -name "*.manifest" -exec grep -oP '^kernel - \K.*?(?=~|-\d+-)' {} \;)" >> $GITHUB_ENV
          cp $OPENWRT_PATH/.config ./build.config
          mv -f $OPENWRT_PATH/bin/packages/*/*/*.*pk packages
          tar -zcf ./Packages.tar.gz packages
          rm -rf packages feeds.buildinfo version.buildinfo
          WIFI=""
          if [ $WRT_TARGET == "JDCloud" ]; then
            WRT_TARGET="IPQ60XX"
            WIFI="-WiFi"
          fi
          if [ $WRT_TARGET == "JDCloud.NoWiFi" ]; then
            WRT_TARGET="IPQ60XX"
            WIFI="-NoWiFi"
          fi
          for FILE in $(find ./ -type f -iname "*$WRT_TARGET*") ; do
            EXT=$(basename $FILE | cut -d '.' -f 2-)
            FULL_NAME=$(basename $FILE | cut -d '.' -f 1)
            PREFIX_NAME=$(basename $FILE | cut -d '.' -f 1 | grep -io ".*\($WRT_TARGET\)" | cut -d '-' -f -2)
            SUFFIX_NAME=$(basename $FILE | cut -d '.' -f 1 | grep -io "\($WRT_TARGET\).*")
            NEW_FILE="$PREFIX_NAME"-"R$FILE_DATE$WIFI"-"$SUFFIX_NAME"."$EXT"
            mv -f $FILE ./$NEW_FILE
          done
          echo "==============================="
          ls $OPENWRT_PATH/bin/targets/*/*
          echo "==============================="
          echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV

      - name: Upload Firmware To Release
        if: steps.compile.outputs.status == 'success'
        uses: ncipollo/release-action@main
        with:
          name: ${{ env.FIRMWARE_TAG }} with ${{ env.FIRMWARE_SOURCE }} at ${{ env.DATE }}
          allowUpdates: true
          removeArtifacts: true
          makeLatest: true
          tag: ${{ env.FIRMWARE_TAG }}-${{ env.FIRMWARE_SOURCE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.FIRMWARE_PATH }}/*
          body: |
            **This is OpenWrt Firmware for ${{ env.FIRMWARE_TAG }} with ${{ env.FIRMWARE_SOURCE }} at ${{ env.DATE }}.**
            ### 📒 固件信息
            - ${{ env.FIRMWARE_BODY }}
            - 💻 这是 ${{ env.FIRMWARE_TAG }} 平台使用的 ${{ env.FIRMWARE_SOURCE }} OpenWrt 固件
            - ⚽ 固件源码: ${{ env.REPO_URL }}
            - 💝 源码分支: ${{ env.REPO_BRANCH }}
            - 🌐 默认地址: **192.168.10.1**
            - 🔑 默认密码: 无
            ### 🧊 固件版本
            - 固件内核版本：${{ env.VERSION_KERNEL }}
            - 固件编译前最后一次➦[主源码](${{ env.REPO_URL }})更新记录
            - ${{ env.VERSION_INFO }}
            ### 🧊 插件
            - 插件：$(grep -oP "luci-app(-[a-zA-Z0-9]{1,}){1,}" ./firmware/*.manifest | awk -F":" '{print $NF}')
            

